# NUMPY

#### NumPy (Numerical Python) is a powerful Python library used for numerical computing. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is the foundation for most scientific computing libraries in Python, such as pandas, SciPy, and scikit-learn.

In [ ]:
import numpy as np
#creating a 1D array
arr=np.array([1,2,3,4,5])
print(arr) # create arra

In [2]:
# .shape-with the help of shape you can check the shape(dimension) of an array
ard=np.array([[1,2],[3,4]])
print(ard)

[[1 2]
 [3 4]]


In [3]:
#array cretion function
zeros=np.zeros((3,3))
ones=np.ones((2,2))
range_arr=np.arange(0,10,2)
linspace_arr=np.linspace(0,1,5)
print(zeros)
print(ones)
print(range_arr)
print(linspace_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [4]:
#array opertion
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
#Element wise additon 
sum_arr=arr1+arr2
print(sum_arr)

[ 6  8 10 12]


In [5]:
#broadcasting
arr=np.array([1,2,3,4])
result=arr+5
print(result)

[6 7 8 9]


In [6]:
#Mathematical operations
data=np.array([5,6,7,7,8])
print(np.mean(data)) #mean 

6.6


In [7]:
yes=np.array([5,6.9,8,8])
print(np.median(yes)) #median 

7.45


In [8]:
yess=np.array([5,6,7,8,9,1,2,3,4,9])
print(np.std(yess)) #standard deviation

2.727636339397171


In [9]:
yee=np.array([4,5,5,5,6,9,8,7])
print(np.sum(yee))

49


In [10]:
#Array indexing and slicing
arr=np.array([10,20,30,40,50])
print(arr[3]) #access the third element
#arr[1:4]=[100,200,300] #modify elements in the range 

40


In [11]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
result=np.dot(A,B) #matrix mulitplication
print(result)

[[19 22]
 [43 50]]


In [12]:
# Random modules
random_arr=np.random.rand(5,5)
print(random_arr)

[[0.07395026 0.2606138  0.70750748 0.88114485 0.92988909]
 [0.73251834 0.19284447 0.17543432 0.59937947 0.65596238]
 [0.68117862 0.53414396 0.96763682 0.93642625 0.401912  ]
 [0.87119175 0.46325721 0.44024583 0.19333662 0.6543713 ]
 [0.70779231 0.82269343 0.24131362 0.12792112 0.89333361]]


In [13]:
# to get the shape of an array
arr=np.array([[1,2],[3,4]])
print(np.shape(arr)) # means it is 2D array 

(2, 2)


In [14]:
# to change the shape of array
arr=np.array([1,2,3,4,5,6])
print(np.reshape(arr,(2,3)))   

[[1 2 3]
 [4 5 6]]


In [15]:
# to transpose array
arr=np.array([[1,2],[3,4]])
transpose_arr=np.transpose(arr)
print(transpose_arr) 

[[1 3]
 [2 4]]


In [16]:
# to sum of array
arr=np.array([1,2,3,5,9,10])
print(np.sum(arr))

30


In [17]:
# to check min. and max. in array
arr=np.array([1,2,3,4,5,])
print(np.min(arr))
print(np.max(arr))

1
5


In [18]:
# it return the index of the smallest and largest numbere respectively
arr=np.array([1,2,3,4,5,6,7])
print(np.argmin(arr))
print(np.argmax(arr))

0
6


In [19]:
# it return the sorted unique element of an array
arr=np.array([1,2,3,4,7,5,4,3,2,1])
print(np.unique(arr))

[1 2 3 4 5 7]


In [20]:
# function to cancatenate
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8]) 
result=np.concatenate((arr1,arr2))
print(result)

[1 2 3 4 5 6 7 8]


In [21]:
# split array into sub arrays
arr=np.array([1,2,3,4,5,6,7,8,9])
result=np.split(arr,3)  
print(result)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [22]:
# generate an array of random no. between 0 and 1
rand_arr=np.random.rand(2,3)
print(rand_arr)

[[0.73543289 0.40721611 0.9049561 ]
 [0.05637149 0.03344036 0.8688744 ]]


In [23]:
# to generate random intergers within a specified range
rand_int_arr=np.random.randint(0,10,size=(2,3))
print(rand_int_arr)

[[1 6 2]
 [2 3 3]]


In [24]:
# array multiplication 
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,9]])
result=np.dot(A,B)
print(result)

[[19 24]
 [43 54]]


In [25]:
# equal space :-
linspace_arr=np.linspace(0,1,5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [26]:
# eye function
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
arr=np.array([1,2,3,4])
arr1=arr
arr1[1]=7
print(arr)
print(arr1)

[1 7 3 4]
[1 7 3 4]


In [28]:
arr=np.array([1,2,3,4])
arr.shape           #reshape by vikram sir
arr=arr.reshape((2,2))
print(arr)

[[1 2]
 [3 4]]


In [29]:
np.split(arr,[0,2,3])

[array([], shape=(0, 2), dtype=int64),
 array([[1, 2],
        [3, 4]]),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64)]

In [30]:
# array multiplication using matmul function
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,9]])
result=np.matmul(A,B)
print(result)

[[19 24]
 [43 54]]


In [31]:
#flatten 
arr=np.array([[1,2,3],[3,4,5],[6,7,8]])
a=arr.flatten(order='c') #here c for row wise
print(a)

[1 2 3 3 4 5 6 7 8]


In [32]:
#flatten 
arr=np.array([[1,2,3],[3,4,5],[6,7,8]])
a=arr.flatten(order='f') #here f-for column wise
print(a)

[1 3 6 2 4 7 3 5 8]


In [33]:
import numpy as np 
#create an empty 2x3 array
arr=np.empty((2,3))
print(arr)

[[0.73543289 0.40721611 0.9049561 ]
 [0.05637149 0.03344036 0.8688744 ]]


In [ ]:
#find indices of non zero elements[1,2,0,0,4,0]
import numpy as np
#create the array
arr=np.array([1,2,0,0,4,0])
zeros=np.nonzero(arr)
print('Indices of non zero elements:',zeros)

In [59]:
# create a null vector of size 10
import numpy as np
null=np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [60]:
#create a null vector of size 10 but the fifth value which is 1
import numpy as np
null=np.zeros(10) #here create null vector soze of 10
null[4]=1 # and here we are initialize 1 value to 4
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [61]:
# Reverse a vector (first element becomes last)
import numpy as np
vector=np.array([1,2,3,4,5,6,7])
reversed_vector=vector[::-1] # here reversing vector with the help of slicing ::-1
print(reversed_vector)

[7 6 5 4 3 2 1]


In [62]:
#create a 3x3 matrix with values ranging form 0 to 8
import numpy as np 
arr=np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
#create a 3x3 identity matrix
import numpy as np
identity_matrix=np.eye(3) # eye use for creating identity matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [64]:
#create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
# Create a 10x10 array with random values between 0 and 1
random = np.random.rand(10, 10)
minn=np.min(random)
maxn=np.max(random)
print(random) 

[[0.23912422 0.76050911 0.81318876 0.93543972 0.69355269 0.14124208
  0.87434986 0.73123247 0.52044806 0.09977478]
 [0.61741676 0.76681975 0.04176778 0.52020183 0.18702816 0.2702105
  0.20335722 0.11932149 0.06763596 0.40845279]
 [0.02446619 0.31084672 0.18893217 0.54859248 0.85046898 0.03375011
  0.94387763 0.52541306 0.41332198 0.27438404]
 [0.39274933 0.96376235 0.64362799 0.13760661 0.27261349 0.25398245
  0.58250747 0.75132206 0.41671522 0.16371487]
 [0.38241273 0.54806579 0.19629553 0.97263621 0.89300314 0.47066924
  0.40203161 0.52919248 0.51068506 0.71443175]
 [0.74857616 0.52618961 0.94780461 0.81450918 0.71111328 0.42983346
  0.11734067 0.31837165 0.89007456 0.38561774]
 [0.77516859 0.10924906 0.75636104 0.12370502 0.06455913 0.08707717
  0.45980496 0.76097163 0.60354964 0.05972804]
 [0.38427761 0.41678159 0.83242371 0.1072542  0.3746818  0.5363716
  0.98587535 0.66481866 0.33780576 0.14542136]
 [0.77632516 0.52229423 0.06383018 0.79411333 0.9463915  0.11073734
  0.97613725 0

In [65]:
#create a random vector of size 30 and find mean value
type([[5]])

list

In [66]:
arr=np.array([5])
s=np.ndim(arr)
print(s) 

1


In [67]:
#create a random vector of size 30 and find mean
import numpy as np 
random=np.random.rand(30)
print(random)
arr=np.mean(random) 

[0.67386913 0.735862   0.6309962  0.87910232 0.77074849 0.39282443
 0.67280158 0.29080893 0.94471083 0.86084868 0.8948413  0.48061027
 0.6350229  0.19687598 0.5278581  0.19918858 0.64028133 0.34660021
 0.26613573 0.63584873 0.05329323 0.26758893 0.80874178 0.91184971
 0.71291539 0.46320224 0.29543884 0.33457736 0.30968401 0.51418828]


In [68]:
#create a 2D array with 1 on the border and 0 inside
import numpy as np
#create a 2D array of size 5x5 with all element initializing to 0
arr=np.zeros((5,5))
#set the border elements to 1
arr[0:5:4]=1
arr[::,0:5:4]=1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
import numpy as np
arr=np.array([1,1,2,3],ndmin=5)
print(arr)
arr.ndim

[[[[[1 1 2 3]]]]]


5

In [70]:
# boolean indexing 
import numpy as np
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])
# Condition: select elements greater than 3
selected_elements = arr[arr > 3]
print(selected_elements) 

[4 5 6]


In [71]:
arr[0:4:5]=1
print(arr)

[1 2 3 4 5 6]


In [72]:
arr[::4]=1
print(arr)

[1 2 3 4 1 6]


In [73]:
arr=np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[::2])

[20 30 40]
[10 30 50]


In [74]:
# find determinant of matrix
import numpy as np
arr=np.array([[1,2],[4,5]])
determinant=np.linalg.det(arr)
print("determinant",determinant)

determinant -2.9999999999999996


In [75]:
#find inverse of matrix
import numpy as np
# Define a 2x2 matrix
A = np.array([[4, 7], 
              [2, 6]])
# Compute the inverse
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A) 

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [76]:
'''1. Array Manipulation
🔹 Generate a 5×5 matrix where elements on the border are 1, and the inside is 0.
# Expected Output:
# [[1. 1. 1. 1. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 1. 1. 1. 1.]]
🔹 Reshape a 1D array of 20 elements into a 4×5 matrix without using reshape().
🔹 Rotate a given 4×4 NumPy array by 90 degrees counterclockwise.
🔹 Flatten a 3D NumPy array into a 1D array.'''
import numpy as py
arr=np.zeros((5,5))
arr[0:4:4,0:4:4]=1
arr[-1::]=1
arr[:,0]=1
arr[:,4]=1
print(arr) #elements on the border are 1, and the inside is 0
arr=np.array([[1,2,3,4,5],[6,7,8,9,5]]) 
reshaped=arr.reshape((1,10))
print(arr) #reshaped
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr=arr.flatten() #flatten array
print(arr)
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])
arr3=np.rot90(arr2,k=1) 
print(arr3) 

[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1 2 3 4 5]
 [6 7 8 9 5]]
[1 2 3 4 5 6 7 8 9]
[[4 8 3]
 [3 7 2]
 [2 6 1]
 [1 5 9]]


In [77]:
#Normal distibution
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))
x

array([[ 0.52422894,  4.68835613, -1.4358141 ],
       [ 0.72171232,  3.34093874,  1.88401973]])

In [78]:
#binomial distribution
from numpy import random
y=random.binomial(n=10,p=0.5,size=10)
y

array([5, 6, 4, 6, 3, 7, 2, 2, 4, 5], dtype=int32)

In [79]:
#Poisson distribution
from numpy import random
x=random.poisson(lam=2,size=10)
x

array([1, 2, 2, 0, 6, 2, 3, 1, 3, 2], dtype=int32)

In [80]:
#Uniform Distribution
from numpy import random 
x=random.uniform(size=(2,3))
x

array([[0.51585555, 0.13325746, 0.73662095],
       [0.12509618, 0.97472687, 0.16938342]])